# Generated by Django 5.2.17 on 2026-10-02 20:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0002_server_pubkey_fp'),
    ]

    operations = [
        migrations.CreateModel(
            name='HAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='rd.asandesk.ir', max_length=200, verbose_name='دامنهٔ عمومی')),
                ('method', models.CharField(choices=[('dns', 'تغییر رکورد DNS'), ('vip', 'IP شناور (keepalived)')], default='dns', max_length=8)),
                ('interval', models.PositiveSmallIntegerField(default=5, verbose_name='فاصلهٔ بررسی سلامت (ثانیه)')),
                ('fails', models.PositiveSmallIntegerField(default=3, verbose_name='خطای پشت\u200cسرهم قبل از جابه\u200cجایی')),
                ('failback', models.BooleanField(default=True, verbose_name='برگشت خودکار به سرور اصلی')),
            ],
        ),
        migrations.CreateModel(
            name='HAEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('kind', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=300)),
                ('by', models.CharField(default='system', max_length=150)),
            ],
            options={
                'ordering': ['-ts', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HAServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('address', models.CharField(max_length=200, verbose_name='IP یا دامنه')),
                ('role', models.CharField(choices=[('primary', 'اصلی'), ('backup', 'پشتیبان')], default='backup', max_length=8)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('id_port', models.PositiveIntegerField(default=21116)),
                ('relay_port', models.PositiveIntegerField(default=21117)),
                ('maintenance', models.BooleanField(default=False, verbose_name='خارج از چرخه (تعمیرات)')),
                ('draft', models.BooleanField(default=False)),
                ('status', models.CharField(default='unknown', max_length=12)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('ports', models.JSONField(blank=True, default=dict)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('fail_count', models.PositiveSmallIntegerField(default=0)),
                ('serving', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ha', to='monitoring.server')),
            ],
            options={
                'ordering': ['priority', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HACheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ms', models.IntegerField(blank=True, null=True)),
                ('ok', models.BooleanField(default=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='ha.haserver')),
            ],
            options={
                'indexes': [models.Index(fields=['server', 'ts'], name='ha_hacheck_server__1f5d98_idx')],
            },
        ),
    ]
