# Generated by Django 5.2.17 on 2026-10-01 07:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="نام"),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=64, verbose_name="منطقه"),
                ),
                ("ip", models.CharField(blank=True, max_length=64, verbose_name="IP")),
                (
                    "hostname",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=128,
                        verbose_name="hostname",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "maintenance",
                    models.BooleanField(default=False, verbose_name="در حال نگهداری"),
                ),
                ("cores", models.PositiveIntegerField(default=0, editable=False)),
                ("ram_total", models.BigIntegerField(default=0, editable=False)),
                ("disk_total", models.BigIntegerField(default=0, editable=False)),
                ("net_capacity_bps", models.BigIntegerField(default=0, editable=False)),
                (
                    "agent_version",
                    models.CharField(blank=True, editable=False, max_length=32),
                ),
                (
                    "first_seen",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_seen",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "سرور",
                "verbose_name_plural": "سرورها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MetricSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(db_index=True)),
                ("cpu", models.FloatField()),
                ("ram", models.FloatField()),
                ("ram_used", models.BigIntegerField(default=0)),
                ("disk", models.FloatField()),
                ("disk_used", models.BigIntegerField(default=0)),
                ("net_rx_bps", models.BigIntegerField(default=0)),
                ("net_tx_bps", models.BigIntegerField(default=0)),
                ("net_pct", models.FloatField(default=0)),
                ("tcp_established", models.PositiveIntegerField(default=0)),
                ("load1", models.FloatField(default=0)),
                ("latency_ms", models.FloatField(blank=True, null=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="monitoring.server",
                    ),
                ),
            ],
            options={
                "ordering": ["ts"],
                "indexes": [
                    models.Index(
                        fields=["server", "ts"], name="monitoring__server__95d88d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("crit", "بحرانی"),
                            ("warn", "هشدار"),
                            ("info", "اطلاع"),
                        ],
                        max_length=8,
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=200)),
                ("detail", models.CharField(blank=True, max_length=300)),
                (
                    "opened_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="monitoring.server",
                    ),
                ),
            ],
            options={
                "verbose_name": "هشدار",
                "verbose_name_plural": "هشدارها",
                "ordering": ["-opened_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolved_at__isnull", True)),
                        fields=("server", "kind"),
                        name="one_open_alert_per_kind",
                    )
                ],
            },
        ),
    ]
