# Generated by Django 5.2.17 on 2026-10-01 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="نام"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="رمز عبور")),
                (
                    "plan",
                    models.CharField(
                        choices=[("free", "رایگان"), ("pro", "حرفه\u200cای")],
                        default="free",
                        max_length=8,
                        verbose_name="طرح",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_login",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "verbose_name": "حساب کاربری اپلیکیشن",
                "verbose_name_plural": "حساب\u200cهای کاربری اپلیکیشن",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rd_id",
                    models.CharField(max_length=32, unique=True, verbose_name="شناسه"),
                ),
                (
                    "uuid_hash",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="نام دستگاه"
                    ),
                ),
                (
                    "os_user",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="کاربر سیستم\u200cعامل"
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="سیستم\u200cعامل"
                    ),
                ),
                (
                    "cpu",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="پردازنده"
                    ),
                ),
                (
                    "memory",
                    models.CharField(blank=True, max_length=32, verbose_name="حافظه"),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="نسخه برنامه"
                    ),
                ),
                ("ip", models.CharField(blank=True, max_length=64, verbose_name="IP")),
                ("blocked", models.BooleanField(default=False, verbose_name="مسدود")),
                (
                    "first_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="اولین تماس"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین تماس"
                    ),
                ),
                (
                    "sysinfo_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to="clients.account",
                        verbose_name="حساب واردشده",
                    ),
                ),
            ],
            options={
                "verbose_name": "کلاینت",
                "verbose_name_plural": "کلاینت\u200cها",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="clients.account",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="clients.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                (
                    "category",
                    models.CharField(blank=True, max_length=64, verbose_name="دسته"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "فوری"),
                            ("high", "بالا"),
                            ("normal", "عادی"),
                            ("low", "کم"),
                        ],
                        default="normal",
                        max_length=8,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "باز"),
                            ("pending", "در انتظار کاربر"),
                            ("closed", "بسته"),
                        ],
                        default="open",
                        max_length=8,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "diag",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="اطلاعات پیوست"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_response_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="clients.client",
                        verbose_name="کلاینت",
                    ),
                ),
            ],
            options={
                "verbose_name": "تیکت",
                "verbose_name_plural": "تیکت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_client", models.BooleanField(default=True)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="clients.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ConnSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conn_id", models.IntegerField()),
                ("session_id", models.CharField(blank=True, max_length=24)),
                ("peer_id", models.CharField(blank=True, db_index=True, max_length=32)),
                ("peer_name", models.CharField(blank=True, max_length=128)),
                ("conn_type", models.SmallIntegerField(blank=True, null=True)),
                ("ip", models.CharField(blank=True, max_length=64)),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "authorized_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "conn_id", "ended_at"],
                        name="clients_con_client__61c416_idx",
                    )
                ],
            },
        ),
    ]
