# Generated by Django 5.2.18 on 2026-10-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_share_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'بازخورد', 'verbose_name_plural': 'بازخوردها'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact',
            field=models.CharField(blank=True, max_length=120, verbose_name='راه تماس'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='log_file',
            field=models.FileField(blank=True, max_length=255, upload_to='feedback-logs/%Y/%m', verbose_name='لاگ برنامه'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='log_files',
            field=models.JSONField(blank=True, default=list, verbose_name='فایل\u200cهای داخل لاگ'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='log_size',
            field=models.PositiveIntegerField(default=0, verbose_name='حجم لاگ (بایت)'),
        ),
    ]
