# Generated by Django 5.2.17 on 2026-10-02 20:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('auto', 'خودکار'), ('manual', 'دستی'), ('safety', 'ایمنی'), ('uploaded', 'بارگذاری\u200cشده')], max_length=12)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('size', models.BigIntegerField(default=0)),
                ('include_files', models.BooleanField(default=False)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='فعال')),
                ('run_time', models.TimeField(default=datetime.time(3, 0), verbose_name='ساعت اجرای روزانه')),
                ('keep_days', models.PositiveSmallIntegerField(default=14, verbose_name='نگهداری (روز)')),
                ('include_files', models.BooleanField(default=False, verbose_name='شامل فایل\u200cهای نصب نسخه\u200cها')),
                ('last_auto_date', models.DateField(blank=True, null=True, verbose_name='آخرین روز اجرای خودکار')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('backup', 'پشتیبان\u200cگیری'), ('restore', 'بازگردانی')], max_length=10)),
                ('trigger', models.CharField(default='manual', max_length=10)),
                ('status', models.CharField(choices=[('queued', 'در صف'), ('running', 'در حال اجرا'), ('ok', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شد')], default='queued', max_length=10)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('pct', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.CharField(blank=True, max_length=200)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('message', models.CharField(blank=True, max_length=400)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('cancellable', models.BooleanField(default=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backups.backup')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
