# Generated by Django 5.2.17 on 2026-10-01 07:47

import django.db.models.deletion
import releases.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(max_length=32, unique=True, verbose_name="نسخه"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("stable", "پایدار"), ("beta", "بتا")],
                        default="stable",
                        max_length=8,
                        verbose_name="کانال",
                    ),
                ),
                ("published_on", models.DateField(verbose_name="تاریخ انتشار")),
                (
                    "platforms",
                    models.JSONField(default=list, verbose_name="پلتفرم\u200cها"),
                ),
                ("notes", models.TextField(verbose_name="توضیحات تغییرات")),
                (
                    "mandatory",
                    models.BooleanField(default=False, verbose_name="اجباری"),
                ),
                (
                    "rollout",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="انتشار تدریجی (٪)"
                    ),
                ),
                (
                    "downloads",
                    models.PositiveIntegerField(default=0, verbose_name="دانلود"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "نسخه",
                "verbose_name_plural": "نسخه\u200cها",
                "ordering": ["-published_on", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DownloadEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=16)),
                ("ts", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_events",
                        to="releases.release",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReleaseAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Windows", "Windows"),
                            ("macOS", "macOS"),
                            ("Linux", "Linux"),
                            ("Android", "Android"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255, upload_to=releases.models.asset_upload_to
                    ),
                ),
                ("size", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="releases.release",
                    ),
                ),
            ],
            options={
                "ordering": ["platform"],
                "unique_together": {("release", "platform")},
            },
        ),
    ]
