# Generated by Django 5.2.18 on 2026-10-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='build',
            field=models.PositiveIntegerField(default=0, verbose_name='شمارهٔ بیلد'),
        ),
        migrations.AddField(
            model_name='release',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='release',
            name='maintenance',
            field=models.BooleanField(default=False, verbose_name='حالت تعمیر'),
        ),
        migrations.AddField(
            model_name='release',
            name='message',
            field=models.CharField(blank=True, max_length=500, verbose_name='پیام به کاربران'),
        ),
        migrations.AddField(
            model_name='releaseasset',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
