# Generated by Django 5.2.18 on 2026-10-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_update_json_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='bale_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='آیدی بله'),
        ),
        migrations.AddField(
            model_name='release',
            name='bale_url',
            field=models.CharField(blank=True, default='https://ble.ir/join/AqZGNkLToJ', max_length=200, verbose_name='لینک کانال بله'),
        ),
    ]
